package Entity.BlockType;

public enum BlockTypeEnum
{
    DESTRUCTIBLE_BLOCK_GROUND,
    DESTRUCTIBLE_BLOCK_LANDMINE,
    DESTRUCTIBLE_BLOCK_HIDDENBLOCK,
    EMPTY_BLOCK,
    EXIT_BLOCK,
    INDESTRUCTIBLE_BLOCK,
    LAVA_BLOCK,
    SPAWNER_BLOCK,
    TELEPORTER_BLOCK
}

