package Entity.BlockType;

public enum BlockTypeEnum
{
    DESTRUCTIBLE_BLOCK,
    DESTRUCTIBLE_BLOCK_LANDMINE,
    DESTRUCTIBLE_BLOCK_SPAWNER,
    EXIT_BLOCK,
    INDESTRUCTIBLE_BLOCK,
    LAVA_BLOCK,
    SPAWNER_BLOCK,
    TELEPORTER_BLOCK
}

